name: 'runx'
description: 'Magical Infrastructure and Deploys'
inputs:
  image:
    description: 'The local image being deployed, provided in the form <IMAGE_NAME>:<IMAGE_TAG>'
    required: true
  env:
    description: 'The name of your environment as defined in your runx config files'
    required: true
  tag:
    description: 'The tag associated with this image. Defaults to the tag on the "image" input field'
    required: false
  conf:
    description: 'The location of the opta config file. Defaults to "opta.yml" in the root dir'
    required: false


runs:
  using: "composite"
  steps:
    - name: Update deployment
      shell: bash    
      run: |
        rm -rf .terraform*
        VERSION=0.9 /bin/bash -c "$(curl -fsSL https://docs.runx.dev/install.sh)"
        CONF=${CONF:-'opta.yml'}
        if [ -z "$TAG" ]
        then
          ~/.opta/opta push $IMAGE --env $RUNX_ENV --conf $CONF
        else
          ~/.opta/opta push $IMAGE --env $RUNX_ENV --tag $TAG --conf $CONF
        fi
        bash -c "yes || true" | ~/.opta/opta apply --var tag=$TAG --env $RUNX_ENV
      env:
        RUNX_ENV: ${{ inputs.env }}
        IMAGE: ${{ inputs.image }}
        TAG: ${{ inputs.tag }}
        CONF: ${{ inputs.conf }}
