name: 'runx'
description: 'Magical Infrastructure and Deploys'
inputs:
  image:
    description: 'The local image being deployed, provided in the form <IMAGE_NAME>:<IMAGE_TAG>'
    required: true
  env:
    description: 'The name of your environment as defined in your runx config files'
    required: true
  tag:
    description: 'The tag associated with this image. Defaults to the tag on the "image" input field'
    required: false
  config:
    description: 'The location of the opta config file. Defaults to "opta.yml" in the root dir'
    required: false
    default: 'opta.yml'


runs:
  using: "composite"
  steps:
    - name: Update deployment
      shell: bash
      run: ./deploy.sh
      env:
        OPTA_ENV: ${{ inputs.env }}
        IMAGE: ${{ inputs.image }}
        TAG: ${{ inputs.tag }}
        CONFIG: ${{ inputs.config }}
